clear;
clc;

RS=[10 12 14 30 40];
REQS=0;REQp1=0;

for i=1:1:5
    REQS=REQS+RS(1,i);
    REQp1=REQp1+(1/RS(1,i));
end
REQp=1/REQp1;
disp("A RESISTENCIA EQUIVALENTE EM SERIE DADA EM OHMS:",REQS);
disp("A RESISTENCIA EQUIVALENTE EM PARALELO DADA EM OHMS:",REQp);
